### ISSUE TITLE
latest melodic release 0.3.6 breaks rviz on buildfarm

### ISSUE THREAD

**Issue by rhaschke** [ros-visualization/python_qt_binding#76]
@dirk-thomas, yesterday's release of python_qt_binding (https://github.com/ros/rosdistro/pull/22454) breaks all rviz binary builds on the build farm, e.g. http://build.ros.org/job/Mbin_ds_dS64__rviz__debian_stretch_amd64__binary/6/display/redirect
Any idea, why cmake cannot find python_qt_binding anymore?

**Comment by dirk-thomas** [comment]
As of #75 the package uses the conditional attributes for the dependencies. It seems that `bloom` isn't including the dependencies in the `control` file. @wjwwood @nuclearsandwich ?

**Comment by nuclearsandwich** [comment]
I can't assign myself to this issue but I am looking into it.

**Comment by nuclearsandwich** [comment]
The issue is that bloom only allows conditions that it can determine from the distribution index and the python version is not currently one of them. (See https://github.com/ros-infrastructure/bloom/pull/519 for the PR which introduced the behavior and why the local environment isn't used.) An addition to the index to specify the python version is being proposed to provide a source for that information and we'll likely also need to add something to bloom which allows user-specified conditions to be used.

To resolve the immediate issue, I've used a patched version of bloom to create a package revision with the ROS_PYTHON_VERSION defined.

https://github.com/ros/rosdistro/pull/22483
