### ISSUE TITLE
Failing installation on Ros due to PyQt5 issue

### ISSUE THREAD

**Issue by tricoveri** [ros-visualization/python_qt_binding#90]
I'm super newbie to Linux. I am trying to install Ros Lunar on an old 32 bit computer with Lubuntu on
I get this message error
```
`Processing catkin package: 'qt_gui_cpp'
==> Building with env: '/home/theo/ros_catkin_ws/install_isolated/env.sh'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/home/theo/ros_catkin_ws/build_isolated/qt_gui_cpp'
==> make -j2 -l2 in '/home/theo/ros_catkin_ws/build_isolated/qt_gui_cpp'
[ 83%] Built target qt_gui_cpp
[ 88%] Running SIP generator for qt_gui_cpp_sip Python bindings...
Traceback (most recent call last):
  File "/home/theo/ros_catkin_ws/install_isolated/share/python_qt_binding/cmake/sip_configure.py", line 9, in <module>
    from PyQt5 import QtCore
ImportError: No module named PyQt5
src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/build.make:89: recipe for target 'sip/qt_gui_cpp_sip/Makefile' failed
make[2]: *** [sip/qt_gui_cpp_sip/Makefile] Error 1
CMakeFiles/Makefile2:374: recipe for target 'src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all' failed
make[1]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
<== Failed to process package 'qt_gui_cpp': 
  Command '['/home/theo/ros_catkin_ws/install_isolated/env.sh', 'make', '-j2', '-l2']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /home/theo/ros_catkin_ws/build_isolated/qt_gui_cpp && /home/theo/ros_catkin_ws/install_isolated/env.sh make -j2 -l2

`
```

Tried to both install PyQt5 using pip command and using alien to turn the .tar.bs into a .deb package.
What directory should I search the package in?
Thanks

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
